# Generated by Django 6.0.2 on 2026-02-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI'), ('CARD', 'Card')], default='COD', max_length=20),
        ),
    ]
